### ISSUE TITLE
Pass not handled correctly by vertex_in_range() method

### ISSUE THREAD

**Issue by marco-1854** [jtauber/gtp#4]
A pass is defined as the tuple (0,0). vertex_in_range() checks to make sure that the x and y of the vertex are greater than or equal to 1. This means that a pass move is defined as illegal.

I would suggest adding a block like this to the beginning of the method like this:

if vertex == PASS:
    return True

**Comment by jtauber** [comment]
The MinimalGame didn't handle this either so I fixed that too (and wrote tests which is how I found the MinimalGame bug)

**Comment by jtauber** [comment]
All fixed with regression tests and released as 0.3

**Comment by marco-1854** [comment]
Beautiful :)
