### ISSUE TITLE
Resignation not handled

### ISSUE THREAD

**Issue by brilee** [jtauber/gtp#5]
I recently connected to CGOS using this gtp library, and of course my program got whooped  :) But I felt guilty about holding up the next round for an unnecessary 5 minutes and was wondering how I might incorporate resignation into my program.

Currently the allowed return values from get_move are tuples (x,y), with (0, 0) signifying pass. Another return value "resign" should be allowable, in which case the GTP genmove should return the string 'resign'.

From GnuGo's GTP/resign page:

```
I'm an author of a GTP client and want to support resignation. What do I need to do?

The GTP command genmove can return either a vertex on the board, the string "pass" or the string "resign". Make sure to handle all these cases appropriately. This is documented in the the GTP version 2 specification draft.
```

**Comment by brilee** [comment]
I'd be happy to take a shot at implementing this - it seems simple enough, even though I'm only very vaguely familiar with how GTP works.

**Comment by jtauber** [comment]
Yeah, I'm happy for you to try implementing "resign". Feel free to do a pull-request, even if work-in-progress for review and discussion.
