### ISSUE TITLE
About gtp.Engine

### ISSUE THREAD

**Issue by KamiYin** [jtauber/gtp#8]
When I used 'gtp.Engine()'
it appeared that
AttributeError: module 'gtp' has no attribute 'Engine'

I had already install gtp, don't  tell me my pip is false!!!

**Comment by jtauber** [comment]
You must have another `gtp.py` file in your path that got imported. Either that or you pip installed the wrong thing (did you `pip install gtp` or `pip install pygtp`?)

**Comment by KamiYin** [comment]
I have already added gtp.py into path. Besides, I ran 'pip install gtp' and 'pip install pygtp' over and over again. But it still was 'module gtp has no engine'

**Comment by KamiYin** [comment]
I did install several gtp setups. Will they conflict？

**Comment by KamiYin** [comment]
After I uninstall gtp, it works!!! It said GTP engine ready. wow~

**Comment by jtauber** [comment]
Yes, the problem is if you `pip install gtp`. The correct one for this package is `pip install pygtp`.
